export const CREATE_ADMIN_REQUEST = "CREATE_ADMIN_REQUEST";
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS";
export const CREATE_ADMIN_FAIL = "CREATE_ADMIN_FAIL";

export const DELETE_RECRUIMENT_REQUEST = "DELETE_RECRUIMENT_REQUEST";
export const DELETE_RECRUIMENT_SUCCESS = "DELETE_RECRUIMENT_SUCCESS";
export const DELETE_RECRUIMENT_FAIL = "DELETE_RECRUIMENT_FAIL";
