export const CREATE_ADMIN_REQUEST = "CREATE_ADMIN_REQUEST";
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS";
export const CREATE_ADMIN_FAIL = "CREATE_ADMIN_FAIL";

export const GET_RECRUIMENT_DETAILS_REQUEST = "GET_RECRUIMENT_DETAILS_REQUEST";
export const GET_RECRUIMENT_DETAILS_SUCCESS = "GET_RECRUIMENT_DETAILS_SUCCESS";
export const GET_RECRUIMENT_DETAILS_FAIL = "GET_RECRUIMENT_DETAILS_FAIL";

export const DELETE_RECRUIMENT_REQUEST = "DELETE_RECRUIMENT_REQUEST";
export const DELETE_RECRUIMENT_SUCCESS = "DELETE_RECRUIMENT_SUCCESS";
export const DELETE_RECRUIMENT_FAIL = "DELETE_RECRUIMENT_FAIL";

export const UPDATE_INFO_ADMIN_REQUEST = "UPDATE_INFO_ADMIN_REQUEST";
export const UPDATE_INFO_ADMIN_SUCCESS = "UPDATE_INFO_ADMIN_SUCCESS";
export const UPDATE_INFO_ADMIN_FAIL = "UPDATE_INFO_ADMIN_FAIL";
